---
marca-diseno:
  git: "git@github.com:noumanity/imagen"
  file: marca.yml
pagina-diseno:
  file: plantilla/404.html.mustache
  schema: schema/404.yml
contenido:
  path: 404.html
  files: 
    - contenido/nohaynada.yml
    - metadata.yml
